server.port=${SERVER_PORT:8081}
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/oficina}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:password}
security.jwt.secret=${SECURITY_JWT_SECRET}
security.jwt.issuer=oficina-auth
security.jwt.audience=oficina-api
